travis:
  secure:
    BINSTAR_TOKEN: i0Oc7ViC87WrnWGcXEXwxas99olLqjWpJYnZNkTVSVg8W2bwg8oQypVx69yk0/cQ9RNIT8k5yRxoiBqm0DSwi1rH8e67TiDD4BtCGNgw6Cu6jPWyi3a2g718unZNur9OQzGZt4em3Q0pgN+geG5L0zAZTAu83BLCy5B0FiBsYRTqd/Z24BgJnkcGjH8rTZjUeciweCsSv7eh8EZszpyDVjlWNxHdann8x8010baSLDQH8SHX397V4GKZs7pfJbYr40radOePL5Nie4/KEmm+AHw0/3WDYJb0XdnehsM7T7Dx0tsmyAd+qkZ2Gxbp0vrZJkIw/oS/eQwD17wKEt5z1BA2ujRy7yGXGmUHymOwQcF+B6hFy6zJ/LlFtY6kgM3Ln+C6AaoRpw03UZXzkn6E0KtUZaNnQsZrWuVbcavsBQCSzWDcPbWwf3b97iLhyWFEI0h3W7aNKoajvoeVDwlHXesBHBXeZni7FxwopL0XYUJs2+CowX/SGOWcwXXCSi5aRcrjNoTexlipQKI6G1ZagaA3J3qhroSqUid7+FKT61zQZuqi5NIAb+OMgavifwitmfTwSYBNBah0sGojqv14cV+jZJeLNR9VdoPFyDYkLICRCLixO+26fqPWOTjlMUbwjDCFGJ/HHGC5oMpe7xVC6j7qSaUVXHgjkK9yGEGH3hk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
